### ISSUE TITLE
Old template when block found

### ISSUE THREAD

**Issue by diomark** [alephium/gpu-miner#10]
right now when a block is mined, a message similar to below is shown -

tid 12094 found it !!
**new block mined, remove the outdated template**
message: 28198
new block: 00000000023ed876de7e3b07ea67956af87f34d81390970cbf763db15a82c5e3
submitted: 0 -> 3: 1

Seems like the template should be updated?

**Comment by polarker** [comment]
> right now when a block is mined, a message similar to below is shown -
> 
> tid 12094 found it !! **new block mined, remove the outdated template** message: 28198 new block: 00000000023ed876de7e3b07ea67956af87f34d81390970cbf763db15a82c5e3 submitted: 0 -> 3: 1
> 
> Seems like the template should be updated?

This is expected. The miner removes the block template used for your just mined block and will wait for new templates.

**Comment by diomark** [comment]
OK tnx for the explanation. I thought this literally meant the message template is old and should be updated.

**Comment by polarker** [comment]
@diomark a bounty is added to thank you for sharing your knowledge with the community

**Comment by diomark** [comment]
> @diomark a bounty is added to thank you for sharing your knowledge with the community

thank you:)

**Comment by polarker** [comment]
@diomark Bounty increased to 200 to thank you for your help on mining community :)

**Comment by polarker** [comment]
@diomark I increased the total bounty to 500. thank you for the help. I am closing this PR for now.
