### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/gpu-miner#16]
please 😊

**Comment by gremaudc** [comment]
For sure ! I have a full AMD rig ready to move from ETH/RVN to ALPH :-)

**Comment by polarker** [comment]
> 

It's coming soon :smiley:

**Comment by diomark** [comment]
Just closing the loop on this - the AMD miner is actually here - https://github.com/alephium/amd-miner
It's working, but doesn't seem to perform as well as the nvidia counterpart..
