### ISSUE TITLE
Add option to output log

### ISSUE THREAD

**Issue by sven-hash** [alephium/gpu-miner#20]
Is it possible to add an cmd line option (like -l ) when the bin/gpu-miner (like `bin/gpu-miner -l /var/log/gpu-miner/hashrate`) is started to set the hashrate output (total hashrate and hashrate per gpu) to be written on a file

The `>>` seems a good option but other programs have some problem to handle it sometimes

**Comment by polarker** [comment]
> Is it possible to add an cmd line option (like -l ) when the bin/gpu-miner (like `bin/gpu-miner -l /var/log/gpu-miner/hashrate`) is started to set the hashrate output (total hashrate and hashrate per gpu) to be written on a file

Is it good enough to use Linux pipe: `bin/gpu-miner &> /var/log/gpu-miner/hashrate` ?

**Comment by sven-hash** [comment]
Yes, it's working, this is how I use it now, but don't know if it possible to implement directly in the source code

I will close the issue, I think other task are more important

**Comment by olivierb2** [comment]
Seems using pipe or redirect is now broken (while I used it few commit ago). It's probably related to this same issue https://github.com/alephium/cpu-miner/issues/7

Can you check ?

**Comment by sven-hash** [comment]
The output is not working as excepted. The log are written every x seconds (like a burst)

**Comment by olivierb2** [comment]
Thanks for the re-open, this is prevent to use latest code on my miners as I can't monitor them without this output parsing.

**Comment by polarker** [comment]
> 
@olivierb2 thanks for the reminder. @sven-hash I just pushed a fixed and released `0.4.3`. Let me know if it works or not

**Comment by olivierb2** [comment]
Hi @polarker, I confirm your fix fixed the issue, I will release the latest code on all my miners.

**Comment by sven-hash** [comment]
Thanks, it's now working

Will close the issue
