### ISSUE TITLE
GPU addressing order

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/gpu-miner#7]
as it looks like, the GPU addressing order in the gpu-miner does not correspond to the order produced by `nvidia-smi -L` or `lspci | grep -i vga`

example:
`./bin/gpu-miner` output:
```
GPU count: 6
GPU #0 has #3584 cores
GPU #1 has #2560 cores
GPU #2 has #2560 cores
GPU #3 has #2560 cores
GPU #4 has #2560 cores
GPU #5 has #1920 cores
```

`nvidia-smi -L` output:
```
GPU 0: NVIDIA GeForce GTX 1080 (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)
GPU 1: NVIDIA GeForce GTX 1080 (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)
GPU 2: NVIDIA GeForce GTX 1080 Ti (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)
GPU 3: NVIDIA GeForce GTX 1080 (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)
GPU 4: NVIDIA GeForce GTX 1080 (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)
GPU 5: NVIDIA GeForce GTX 1070 (UUID: GPU-xxxxxxxx-yyyy-zzzz-xyxy-xyzxyzxyzxyz)

```
`lspci | grep -i vga` output:
```
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 610 (rev 04)
07:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
09:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
0b:00.0 VGA compatible controller: NVIDIA Corporation GP102 [GeForce GTX 1080 Ti] (rev a1)
0c:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
0d:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
0e:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
```

In this example, as you can see, `GPU #0` in `gpu-miner` is the same as `GPU 2` in `nvidia-smi -L`, as well as `0b:00.0` in `lspci`.

A consistent addressing might become relevant in a future pool usage, to identify the card, mining the blocks. Further in a future version of gpu-miner, supporting AMD cards, the order could once more be "messed up".

**Comment by polarker** [comment]
@ferdinandhodl We order the GPUs based on the device id, which should be the best way from an engineering point of view

**Comment by sven-hash** [comment]
Sorry to reopen this issue but I would like to add some information

By default CUDA set the fastest gpu with id 0 but nvidia-smi use the PCI port id, you could set an environnement variable `export CUDA_DEVICE_ORDER=PCI_BUS_ID` when starting the alephium client to have the same id on nvidia-smi and CUDA

For more information ([source](https://discuss.pytorch.org/t/gpu-devices-nvidia-smi-and-cuda-get-device-name-output-appear-inconsistent/13150))
